name: publish-to-github-packages

on:
  workflow_dispatch:

jobs:

  the_job:

    runs-on: ubuntu-latest
    # runs-on: windows-latest

    permissions:
      contents: write

    steps:

    - uses: actions/checkout@v4

    - name: GitHub Tag Bump
      id: tag_bump
      uses: anothrNick/github-tag-action@1.71.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        INITIAL_VERSION: 5.1.0
        DEFAULT_BUMP: patch

    - name: Setup dotnet
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.200

    - name: "Build 'Develop' configuration"
      run: scripts/build.bash Configuration=Develop

    - name: "Publish 'Develop' configuration"
      run: scripts/publish.bash Configuration=Develop ProjectName=${{ github.event.repository.name }} Version=${{ steps.tag_bump.outputs.new_tag }} Address=https://nuget.pkg.github.com/MikeNakis/index.json ApiKey=${{ secrets.MY_GITHUB_TOKEN }}

    - name: "Build 'Release' configuration"
      run: scripts/build.bash Configuration=Release

    - name: "Publish 'Release' configuration"
      run: scripts/publish.bash Configuration=Release ProjectName=${{ github.event.repository.name }} Version=${{ steps.tag_bump.outputs.new_tag }} Address=https://nuget.pkg.github.com/MikeNakis/index.json ApiKey=${{ secrets.MY_GITHUB_TOKEN }}
