name: Build

# PEARL: In GitHub, the output of msbuild looks completely different from what it looks when building locally. For
#        example, the output of "Message" tasks is not shown, even when "Importance" is set to "High".
#        The "-ConsoleLoggerParameters:off" magical incantation corrects this problem.
# PEARL-ON-PEARL: The "-ConsoleLoggerParameters:off" magical incantation does not work when invoking "dotnet build"
#        locally. In this case, the "-TerminalLogger:off" magical incantation is necessary.
#        So, we use -TerminalLogger:off here too, for consistency.

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

# env:
#  BUILD_SERVER_BUILD: True

jobs:
  build:

    runs-on: ubuntu-latest
    # runs-on: windows-latest

    steps:

    - uses: actions/checkout@v4
      with:
        fetch-depth: 0 # A fetch-depth of 0 fetches all history. It is needed for GitVersion.

    # latest gitversion version: 6.3.0
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v3.2.1
      with:
        versionSpec: 6.3.x

    - name: Determine Version
      uses: gittools/actions/gitversion/execute@v3.2.1
      id: gitversion # step id used as reference for output values

    - name: Display GitVersion outputs
      run: |
        git tag
        echo "Version: ${{ steps.gitversion.outputs.SemVer }}"
        echo "CommitsSinceVersionSource: ${{ steps.gitversion.outputs.CommitsSinceVersionSource }}"

    - name: Setup dotnet
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.200

    #- run: echo gitHub.run_number = ${{github.run_number}} gitHub.run_attempt = ${{github.run_attempt}} env.RELEASE_VERSION = ${{env.RELEASE_VERSION}}

    - name: "restore"
      run: dotnet restore    -TerminalLogger:off -check

    - name: "Configuration 'Debug': build"
      run: dotnet build      -TerminalLogger:off -check --configuration Debug --no-restore

    - name: "Configuration 'Debug': test"
      run: dotnet test       -TerminalLogger:off -check --configuration Debug --no-build --verbosity normal

    - name: "Configuration 'Develop': build"
      run: dotnet build      -TerminalLogger:off -check --configuration Develop --no-restore

    - name: "Configuration 'Develop': pack"
      run: dotnet pack       -TerminalLogger:off -check --configuration Develop --no-build --property:PackageVersion=${{ steps.gitversion.outputs.SemVer }}

    - name: "Configuration 'Develop': push"
      run: dotnet nuget push "${{github.event.repository.name}}/bin/Develop/*.nupkg" --source https://api.nuget.org/v3/index.json --api-key ${{secrets.NUGET_API_KEY}}

    - name: "Configuration 'Release': build"
      run: dotnet build      -TerminalLogger:off -check --configuration Release --no-restore

    - name: "Configuration 'Release': pack"
      run: dotnet pack       -TerminalLogger:off -check --configuration Release --no-build --property:PackageVersion=${{ steps.gitversion.outputs.SemVer }}

    - name: "Configuration 'Release': push"
      run: dotnet nuget push "${{github.event.repository.name}}/bin/Release/*.nupkg" --source https://api.nuget.org/v3/index.json --api-key ${{secrets.NUGET_API_KEY}}
